### ISSUE TITLE
How do I keep the original device driver in addition to the CFU driver?

### ISSUE THREAD

**Issue by lgdacunha** [microsoft/CFU#42]
Looks like when I install the CFU driver, it replaces the current device driver of the device I specify on the inf file on [Standard.NT$ARCH$] %ComponentFirmwareUpdate.DeviceDesc%
How do I keep the original device driver in addition to the CFU driver?

**Comment by samtertzakian** [comment]
You should use the inbox CFU driver instead of the driver in this repo (so you don't need to write a driver). Please see:

https://learn.microsoft.com/en-us/windows-hardware/drivers/cfu/
