### ISSUE TITLE
A list of hardware supporting CFU

### ISSUE THREAD

**Issue by hughsie** [microsoft/CFU#43]
Is there list of hardware that supports CFU? I'd like to add cfu support to fwupd and need some hardware to test the implementation. I'm especially interested in devices that have subcomponents with different firmware versions. Thanks.

**Comment by hughsie** [comment]
I'll close this as it's pointless keeping it open. I'm just telling IHVs to completely ignore CFU now.

**Comment by NathanS-Microsoft** [comment]
Hi, @hughsie,

I don't think anyone is tracking this, hardware vendors don't necessarily report back to anyone to create such a list.  Inside Microsoft we use it but we use security features that would make testing it difficult, as you would need images that the devices would accept, including so-called jailbreak or rollback images to repeat tests.
